#
# Vagrantfile for curate_nd
#
#
Vagrant.configure(2) do |config|
  
# Use CentOS image w/puppet already installed

  config.vm.box = "nrel/CentOS-6.5-x86_64"
  config.vm.hostname = "curatend-devl-vm.library.nd.edu"

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Create a private network ip
  config.vm.network "private_network", ip: "192.168.50.2"

  # root folder shared as /vagrant. Share hiera as well 
  config.vm.synced_folder "../puppet/hiera", "/var/lib/hiera"

  # Provider-specific configuration
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
	vb.memory = "4096"
	vb.cpus = 2
        vb.name = "curate-devl-vm"
   end

  # CentOS provisioning
  config.vm.provision "shell", inline: "yum list epel-release || yum -y install epel-release"
  config.vm.provision "shell", inline: "cp -f /vagrant/iptables /etc/sysconfig/iptables && service iptables restart"
  config.vm.provision "shell", inline: "if [ ! -d /etc/puppet/modules/mysql ]; then  puppet module install puppetlabs/mysql; fi"

  #m Enable provisioning with Puppet
  # 
  config.vm.provision :puppet do |puppet|
       puppet.manifests_path     = "../puppet/manifests"
       puppet.manifest_file     = "vagrant.pp"
       puppet.hiera_config_path = "../puppet/hiera.yaml"
       puppet.module_path = [  "/Users/msuhovec/repos/puppet_standalone/modules" , "../puppet/modules" ]
       puppet.options = "--verbose "
  end

  config.vm.provision "shell", inline: "usermod -G app nginx"
end
