# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

AD_API_URL: 'https://api-prep.library.nd.edu/1.0/people/search/'
AD_API_TOKEN: 'TY8HEtx5zsFVBS65-ZcU'

BATCH_INGESTOR_URL: 'http://localhost:15000/'

# Examples only... actual values used are in secrets:
CURATE_HELP_NOTIFICATION_RECIPIENT: curate@nd.edu
CURATE_HELP_NOTIFICATION_DEFAULT_SENDER: curate@nd.edu

# These are keys for the sandbox
ORCID_APP_ID: "0000-0002-6683-6607"
ORCID_APP_SECRET: "e1ff26a2-d889-40be-bd41-acac09214cae"

DOI_USERNAME: "ADD THIS TO YOUR ENV"
DOI_PASSWORD: "ADD THIS TO YOUR ENV"
DOI_SHOULDER: "doi:10.5072/FK2"
DOI_HOST: "ez.test.datacite.org"
DOI_RESOLVER: "https://handle.test.datacite.org"
DOI_PORT: "443"

LDAP_HOST: "directory.nd.edu"
LDAP_PORT: '636'
LDAP_ENCRYPTION: "simple_tls"

OSF_HOST_NAME: 'osf.io'
OSF_SCHEME: 'https'

SENTRY_DSN: 'fakey-mcfake-face'

S3_BUCKET: 'bucket-name'
AWS_ACCESS_KEY_ID: 'abcde'
AWS_SECRET_ACCESS_KEY: 'abcde'

development:
  # Commented out because these create the requirement to start the noids server
  # in order to run in localhost.
  # NOIDS_SERVER: "localhost:13001"
  # NOIDS_POOL: "test"
  ORCID_PERSISTENT_TOKENS_ENABLED: "false"
  ORCID_REDIRECT_URI: "https://localhost:3000/users/auth/orcid/callback"
  ORCID_SITE_URL: "https://sandbox.orcid.org"
  ORCID_TOKEN_URL: "https://sandbox.orcid.org/oauth/token"
  ORCID_REMOTE_SIGNIN_URL: "https://sandbox.orcid.org/signin/auth.json"
  ORCID_HOST_URL: "https://sandbox.orcid.org"
  ORCID_AUTHORIZE_URL: "https://sandbox.orcid.org/oauth/authorize"
  ORCID_SEARCH_URL: "https://sandbox.orcid.org/orcid-search/quick-search"
  okta_auth_server_id: fakey
  okta_auth_url: fakey
  okta_client_id: fakey
  okta_client_secret: fakey
  okta_redirect_uri: fakey
  okta_site: fakey
  okta_token_url: fakey
  bendo_api_key: ''

  # SENTRY_DSN: 'put something here if you want it for testing'

test:
  okta_auth_server_id: fakey
  okta_auth_url: fakey
  okta_client_id: fakey
  okta_client_secret: fakey
  okta_redirect_uri: fakey
  okta_site: fakey
  okta_token_url: fakey

ci:
  okta_auth_server_id: fakey
  okta_auth_url: fakey
  okta_client_id: fakey
  okta_client_secret: fakey
  okta_redirect_uri: fakey
  okta_site: fakey
  okta_token_url: fakey
