#
# FYI: This file is replaced by a copy for deploys
# to ci, pre_production, and production.
#

<%
  socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
  "/var/run/mysql5/mysqld.sock",
  "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["BOXEN_MYSQL_PORT"] || "3306"
  host = ENV["MYSQL_HOST"] || "127.0.0.1"
%>

mysql_connection: &mysql_connection
<% if socket %>
  host: localhost
  socket: <%= socket %>
<% else %>
  host: <%= host %>
  port: <%= port %>
<% end %>

mysql_settings: &mysql_settings
  adapter:   mysql2
  encoding:  utf8
  reconnect: false
  pool:      5

local_user: &local_user
  <<: *mysql_settings
  <<: *mysql_connection
  username: root
  password: password

development: &development
  <<: *local_user
  database: curate_nd_development
  timeout: 5000

development_remote_purl_database:
  <<: *development

test: &test
  <<: *development
  database: curate_nd_test

test_remote_purl_database:
  <<: *test

ci: &ci
  <<: *test

ci_remote_purl_database:
  <<: *ci

metrics_db:
  database: metrics_db_name
  username: metrics_username
  password: metrics_password
  host:     metrics_host
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
